# Generated by Django 4.1.7 on 2023-03-20 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('computingID', models.CharField(max_length=10)),
                ('department', models.JSONField(default=list)),
                ('students', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('section', models.CharField(max_length=300)),
                ('catalog_nbr', models.CharField(default='0000', max_length=300)),
                ('meetings', models.JSONField(default=dict)),
                ('credits', models.CharField(default='3', max_length=300)),
                ('component', models.CharField(default='LEC', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('computingID', models.CharField(max_length=10)),
                ('year', models.IntegerField(default=1)),
                ('department', models.JSONField(default=list)),
                ('majors', models.JSONField(default=list)),
                ('minors', models.JSONField(default=list)),
                ('advisors', models.JSONField(default=list)),
                ('schedules', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student', models.CharField(max_length=100)),
                ('credits', models.IntegerField(default=0)),
                ('courses', models.ManyToManyField(to='advisor_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_advisor', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
