# Generated by Django 3.2.17 on 2023-03-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isapproved',
            field=models.BooleanField(default=False),
        ),
    ]
