# Generated by Django 3.2.17 on 2023-04-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_app', '0004_alter_schedule_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='isapproved',
            field=models.BooleanField(),
        ),
    ]
