# Generated by Django 4.1.5 on 2023-04-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advisor_app", "0007_rename_credits_course_credit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule", old_name="credits", new_name="credit",
        ),
    ]
