# Generated by Django 4.1.7 on 2023-04-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_app', '0008_rename_credits_schedule_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='course_creds',
            field=models.JSONField(default=dict),
        ),
    ]
