# Generated by Django 4.1.7 on 2023-04-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_app', '0009_schedule_course_creds'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
