# Generated by Django 4.1.7 on 2023-04-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_app', '0011_remove_student_advisors_student_advisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='schedules',
            field=models.ManyToManyField(to='advisor_app.schedule'),
        ),
    ]
