# Generated by Django 4.1.7 on 2023-04-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_app', '0012_advisor_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='schedules',
        ),
        migrations.AddField(
            model_name='schedule',
            name='pending_approval',
            field=models.BooleanField(default=False),
        ),
    ]
