# Generated by Django 4.1.7 on 2023-04-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_app', '0013_remove_advisor_schedules_schedule_pending_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='advisors',
        ),
        migrations.AddField(
            model_name='advisor',
            name='students',
            field=models.ManyToManyField(to='advisor_app.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='advisors',
            field=models.JSONField(default=list),
        ),
    ]
