# Generated by Django 4.1.7 on 2023-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_app', '0015_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='isrejected',
            field=models.BooleanField(default=False),
        ),
    ]
